# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 460ff10cca6eb675c17abe313b462abd9e08a95a468e35b47342946956bc27da0b089bfd3bba222ab796396e02820fa33b95b8ce3bf41b411277053fcf6818c1

test:
  secret_key_base: 3599d67c7f800a50feffbefd99129f371e67b23edb432800220a1bce33835b427de2c820d2d0f6d77d690b8c686ff6df8d7d90a8c35ea79aba17097d79561a14

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
